[episodes_params]
# names of which tests to include in the final benchmark
; tests = ['t_ETH1', 't_ETH2', 't_eth_follow', 't_eth_against', 't_eth_dense_flow', 't_eth_dense_against']
tests = [
    't_dhotel_bottopmid', 't_dhotel_bottopmid_2', 
    't_dhotel_bottopleft', 't_dhotel_bottopleft_2', 
    't_dhotel_obstaclest', 't_dhotel_obstaclest_2'
]
# tests = ['t_zara1_basic_cross', 't_zara1_wrap', 't_zara1_dense', 't_zara1_dense_rev','t_zara1_dense_cross', 't_zara1_dense_crosswrap_rev']
#tests = ['t_zara2', 't_zara2_basic_against','t_zara2_wrap', 't_zara2_wrap2', 't_zara2_against_seq']
# tests = ['t_univ1', 't_univ_obstacle', 't_univ_trapTR', 't_univ_trapTR2', 't_univ_trapTL', 't_univ_trapBL','t_univ_trapBR', 't_univ_across',]
# tests = ['t_dhotel_bottopmid', 't_dhotel_bottopleft', 't_dhotel_obstaclest']
; tests = [
;     # ETH scenarios
;     't_ETH1', 't_ETH2', 't_eth_follow', 't_eth_against', 't_eth_dense_flow', 't_eth_dense_against',

;     # Zara scenarios
;     't_zara1_basic_cross', 't_zara1_wrap', 't_zara1_dense', 't_zara1_dense_rev',
;     't_zara1_dense_cross', 't_zara1_dense_crosswrap_rev', 

;     't_zara2', 't_zara2_basic_against','t_zara2_wrap', 't_zara2_wrap2', 't_zara2_against_seq',

;     # Univ scenarios
;     't_univ1', 't_univ_obstacle', 't_univ_trapTR', 't_univ_trapTR2', 't_univ_trapTL', 't_univ_trapBL',
;     't_univ_trapBR', 't_univ_across',

;     # Hotel scenarios
;     't_hotel_against', 't_hotel_follow', 't_hotel_against_diag', 't_hotel_follow_diag', 't_hotel_cross',

;     # Dhotel scenarios
;     't_dhotel_bottopmid', 't_dhotel_bottopleft', 't_dhotel_obstaclest']


without_robot=False ; Whether or not to run a lite-version of the simulator without the robot




# DoubleHotel double corridor with obstacles in the middle
[t_dhotel_bottopmid]
map_name=DoubleHotel
pedestrian_datasets=["dhotel-top", "dhotel-bot"]
datasets_start_t = [0, 0]
ped_ranges=[(140, -1), (180, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[8, 1, -3], [9, 22.5, 1.5]]
max_time=60
write_episode_log=True

[t_dhotel_bottopmid_2]
map_name=DoubleHotel
pedestrian_datasets=["dhotel-top", "dhotel-bot"]
datasets_start_t = [0, 0]
ped_ranges=[(140, -1), (180, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[9, 22.5, 1.5], [8, 1, -3]]
max_time=60
write_episode_log=True

[t_dhotel_bottopleft]
map_name=DoubleHotel
pedestrian_datasets=["dhotel-top", "dhotel-bot"]
datasets_start_t = [0, 0]
ped_ranges=[(140, -1), (180, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[16.5, 2.5, -3], [3, 22.5, 1.5]]
max_time=60
write_episode_log=True

[t_dhotel_bottopleft_2]
map_name=DoubleHotel
pedestrian_datasets=["dhotel-top", "dhotel-bot"]
datasets_start_t = [0, 0]
ped_ranges=[(140, -1), (180, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[3, 22.5, 1.5], [16.5, 2.5, -3]]
max_time=60
write_episode_log=True

[t_dhotel_obstaclest]
map_name=DoubleHotel
pedestrian_datasets=["dhotel-top", "dhotel-bot"]
datasets_start_t = [0, 0]
ped_ranges=[(140, -1), (180, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[4, 10, 0.4], [10, 20, 0.6]]
max_time=60
write_episode_log=True

[t_dhotel_obstaclest_2]
map_name=DoubleHotel
pedestrian_datasets=["dhotel-top", "dhotel-bot"]
datasets_start_t = [0, 0]
ped_ranges=[(140, -1), (180, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[10, 20, 0.6], [4, 10, 0.4]]
max_time=60
write_episode_log=True
