[episodes_params]
# names of which tests to include in the final benchmark
; tests = ['t_ETH1', 't_ETH2', 't_eth_follow', 't_eth_against', 't_eth_dense_flow', 't_eth_dense_against']
tests = [
    't_zara1_1', 't_zara1_2', 't_zara1_3', 't_zara1_4', 't_zara1_5', 't_zara1_6', 't_zara1_7', 
    't_zara1_8', 't_zara1_9', 't_zara1_10', 't_zara1_11', 't_zara1_12', 't_zara1_13', 't_zara1_14', 
    't_zara1_15', 't_zara1_16', 't_zara1_17', 't_zara1_18', 't_zara1_19', 't_zara1_20', 
    't_zara2_1', 't_zara2_2', 't_zara2_3', 't_zara2_4', 't_zara2_5', 't_zara2_6', 't_zara2_7', 
    't_zara2_8', 't_zara2_9', 't_zara2_10', 't_zara2_11', 't_zara2_12', 't_zara2_13', 't_zara2_14', 
    't_zara2_15', 't_zara2_16', 't_zara2_17', 't_zara2_18', 't_zara2_19', 't_zara2_20', 
    't_zara2_21', 't_zara2_22', 't_zara2_23', 't_zara2_24', 't_zara2_25', 't_zara2_26', 't_zara2_27', 
    't_zara2_28', 't_zara2_29', 't_zara2_30', 't_zara2_31', 't_zara2_32', 't_zara2_33', 't_zara2_34', 
    't_zara2_35', 't_zara2_36', 't_zara2_37', 't_zara2_38', 't_zara2_39', 't_zara2_40'
]

# tests = ['t_zara1_basic_cross', 't_zara1_wrap', 't_zara1_dense', 't_zara1_dense_rev','t_zara1_dense_cross', 't_zara1_dense_crosswrap_rev']
#tests = ['t_zara2', 't_zara2_basic_against','t_zara2_wrap', 't_zara2_wrap2', 't_zara2_against_seq']
# tests = ['t_univ1', 't_univ_obstacle', 't_univ_trapTR', 't_univ_trapTR2', 't_univ_trapTL', 't_univ_trapBL','t_univ_trapBR', 't_univ_across',]
# tests = ['t_dhotel_bottopmid', 't_dhotel_bottopleft', 't_dhotel_obstaclest']
; tests = [
;     # ETH scenarios
;     't_ETH1', 't_ETH2', 't_eth_follow', 't_eth_against', 't_eth_dense_flow', 't_eth_dense_against',

;     # Zara scenarios
;     't_zara1_basic_cross', 't_zara1_wrap', 't_zara1_dense', 't_zara1_dense_rev',
;     't_zara1_dense_cross', 't_zara1_dense_crosswrap_rev', 

;     't_zara2', 't_zara2_basic_against','t_zara2_wrap', 't_zara2_wrap2', 't_zara2_against_seq',

;     # Univ scenarios
;     't_univ1', 't_univ_obstacle', 't_univ_trapTR', 't_univ_trapTR2', 't_univ_trapTL', 't_univ_trapBL',
;     't_univ_trapBR', 't_univ_across',

;     # Hotel scenarios
;     't_hotel_against', 't_hotel_follow', 't_hotel_against_diag', 't_hotel_follow_diag', 't_hotel_cross',

;     # Dhotel scenarios
;     't_dhotel_bottopmid', 't_dhotel_bottopleft', 't_dhotel_obstaclest']


without_robot=False ; Whether or not to run a lite-version of the simulator without the robot





[t_zara1_1]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[8.0, 8, 0], [15, 3, -0.2]]
max_time=60
write_episode_log=True

[t_zara1_2]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[15, 3, -0.2], [8.0, 8, 0]]
max_time=60
write_episode_log=True

[t_zara1_3]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[2, 2, 1.8], [17.5, 13, 0]]
max_time=60
write_episode_log=True

[t_zara1_4]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[17.5, 13, 0], [2, 2, 1.8]]
max_time=60
write_episode_log=True

[t_zara1_5]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[19.5, 5, 0], [2, 5, 0]]
max_time=60
write_episode_log=True

[t_zara1_6]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[2, 5, 0], [19.5, 5, 0]]
max_time=60
write_episode_log=True

[t_zara1_7]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[14, 13, -1.5], [14, 1, -1.5]]
max_time=60
write_episode_log=True

[t_zara1_8]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[14, 1, -1.5], [14, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara1_9]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[4, 2, 0], [14, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara1_10]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[14, 13, -1.5], [4, 2, 0]]
max_time=60
write_episode_log=True

[t_zara1_11]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(78, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[8.0, 8, 0], [15, 3, -0.2]]
max_time=60
write_episode_log=True

[t_zara1_12]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(78, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[15, 3, -0.2], [8.0, 8, 0]]
max_time=60
write_episode_log=True

[t_zara1_13]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(78, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[2, 2, 1.8], [17.5, 13, 0]]
max_time=60
write_episode_log=True

[t_zara1_14]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(78, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[17.5, 13, 0], [2, 2, 1.8]]
max_time=60
write_episode_log=True

[t_zara1_15]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(78, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[19.5, 5, 0], [2, 5, 0]]
max_time=60
write_episode_log=True

[t_zara1_16]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(78, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[2, 5, 0], [19.5, 5, 0]]
max_time=60
write_episode_log=True

[t_zara1_17]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(78, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[14, 13, -1.5], [14, 1, -1.5]]
max_time=60
write_episode_log=True

[t_zara1_18]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(78, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[14, 1, -1.5], [14, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara1_19]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(78, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[4, 2, 0], [14, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara1_20]
map_name=Zara
pedestrian_datasets=["zara01"]
datasets_start_t = [0]
ped_ranges=[(78, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[14, 13, -1.5], [4, 2, 0]]
max_time=60
write_episode_log=True

#Zara02
[t_zara2_1]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[8.0, 8.5, 0], [15, 3, -0.2]]
max_time=60
write_episode_log=True

[t_zara2_2]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[15, 3, -0.2], [8.0, 8.5, 0]]
max_time=60
write_episode_log=True

[t_zara2_3]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 5, -3], [1.5, 5, -3]]
max_time=60
write_episode_log=True

[t_zara2_4]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 5, -3], [20, 5, -3]]
max_time=60
write_episode_log=True


[t_zara2_5]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 13, -1.5], [1.5, 8, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_6]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 8, -1.5], [20, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_7]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 13, -1.5], [1.5, 1.5, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_8]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 1.5, -1.5], [20, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_9]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 5, 0], [20, 5, 0]]
max_time=60
write_episode_log=True

[t_zara2_10]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 5, 0], [1.5, 5, 0]]
max_time=60
write_episode_log=True

; -------------- 
; 11 ~ 20 => ped_ranges = [(7, -1)]
; --------------

[t_zara2_11]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(7, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[8.0, 8.5, 0], [15, 3, -0.2]]
max_time=60
write_episode_log=True

[t_zara2_12]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(7, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[15, 3, -0.2], [8.0, 8.5, 0]]
max_time=60
write_episode_log=True

[t_zara2_13]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(7, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 5, -3], [1.5, 5, -3]]
max_time=60
write_episode_log=True

[t_zara2_14]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(7, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 5, -3], [20, 5, -3]]
max_time=60
write_episode_log=True

[t_zara2_15]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(7, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 13, -1.5], [1.5, 8, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_16]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(7, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 8, -1.5], [20, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_17]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(7, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 13, -1.5], [1.5, 1.5, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_18]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(7, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 1.5, -1.5], [20, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_19]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(7, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 5, 0], [20, 5, 0]]
max_time=60
write_episode_log=True

[t_zara2_20]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(7, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 5, 0], [1.5, 5, 0]]
max_time=60
write_episode_log=True

; -------------- 
; 21 ~ 30 => ped_ranges = [(20, -1)]
; --------------

[t_zara2_21]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(20, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[8.0, 8.5, 0], [15, 3, -0.2]]
max_time=60
write_episode_log=True

[t_zara2_22]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(20, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[15, 3, -0.2], [8.0, 8.5, 0]]
max_time=60
write_episode_log=True

[t_zara2_23]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(20, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 5, -3], [1.5, 5, -3]]
max_time=60
write_episode_log=True

[t_zara2_24]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(20, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 5, -3], [20, 5, -3]]
max_time=60
write_episode_log=True

[t_zara2_25]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(20, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 13, -1.5], [1.5, 8, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_26]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(20, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 8, -1.5], [20, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_27]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(20, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 13, -1.5], [1.5, 1.5, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_28]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(20, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 1.5, -1.5], [20, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_29]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(20, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 5, 0], [20, 5, 0]]
max_time=60
write_episode_log=True

[t_zara2_30]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(20, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 5, 0], [1.5, 5, 0]]
max_time=60
write_episode_log=True

; -------------- 
; 31 ~ 40 => ped_ranges = [(44, -1)]
; --------------

[t_zara2_31]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(44, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[8.0, 8.5, 0], [15, 3, -0.2]]
max_time=60
write_episode_log=True

[t_zara2_32]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(44, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[15, 3, -0.2], [8.0, 8.5, 0]]
max_time=60
write_episode_log=True

[t_zara2_33]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(44, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 5, -3], [1.5, 5, -3]]
max_time=60
write_episode_log=True

[t_zara2_34]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(44, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 5, -3], [20, 5, -3]]
max_time=60
write_episode_log=True

[t_zara2_35]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(44, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 13, -1.5], [1.5, 8, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_36]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(44, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 8, -1.5], [20, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_37]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(44, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 13, -1.5], [1.5, 1.5, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_38]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(44, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 1.5, -1.5], [20, 13, -1.5]]
max_time=60
write_episode_log=True

[t_zara2_39]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(44, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 5, 0], [20, 5, 0]]
max_time=60
write_episode_log=True

[t_zara2_40]
map_name=Zara
pedestrian_datasets=["zara02"]
datasets_start_t = [0]
ped_ranges=[(44, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[20, 5, 0], [1.5, 5, 0]]
max_time=60
write_episode_log=True




