[episodes_params]
# names of which tests to include in the final benchmark
; tests = ['t_ETH1', 't_ETH2', 't_eth_follow', 't_eth_against', 't_eth_dense_flow', 't_eth_dense_against']
tests = [
    't_ETH1_1', 't_ETH1_2', 't_ETH1_3', 't_ETH1_4', 't_ETH1_5', 't_ETH1_6', 't_ETH1_7', 't_ETH1_8', 
    't_ETH1_9', 't_ETH1_10', 't_ETH1_11', 't_ETH1_12', 't_ETH1_13', 't_ETH1_14', 't_ETH1_15', 
    't_ETH1_16', 't_ETH1_17', 't_ETH1_18', 't_ETH1_19', 't_ETH1_20', 't_ETH1_21', 't_ETH1_22', 
    't_ETH1_23', 't_ETH1_24', 't_ETH1_25', 't_ETH1_26', 't_ETH1_27', 't_ETH1_28', 't_ETH1_29', 
    't_ETH1_30', 't_ETH1_31', 't_ETH1_32', 't_ETH1_33', 't_ETH1_34', 't_ETH1_35', 't_ETH1_36', 
    't_ETH1_37', 't_ETH1_38', 't_ETH1_39', 't_ETH1_40', 't_ETH1_41', 't_ETH1_42', 't_ETH1_43', 't_ETH1_44'
]
# tests = ['t_zara1_basic_cross', 't_zara1_wrap', 't_zara1_dense', 't_zara1_dense_rev','t_zara1_dense_cross', 't_zara1_dense_crosswrap_rev']
#tests = ['t_zara2', 't_zara2_basic_against','t_zara2_wrap', 't_zara2_wrap2', 't_zara2_against_seq']
# tests = ['t_univ1', 't_univ_obstacle', 't_univ_trapTR', 't_univ_trapTR2', 't_univ_trapTL', 't_univ_trapBL','t_univ_trapBR', 't_univ_across',]
# tests = ['t_dhotel_bottopmid', 't_dhotel_bottopleft', 't_dhotel_obstaclest']
; tests = [
;     # ETH scenarios
;     't_ETH1', 't_ETH2', 't_eth_follow', 't_eth_against', 't_eth_dense_flow', 't_eth_dense_against',

;     # Zara scenarios
;     't_zara1_basic_cross', 't_zara1_wrap', 't_zara1_dense', 't_zara1_dense_rev',
;     't_zara1_dense_cross', 't_zara1_dense_crosswrap_rev', 

;     't_zara2', 't_zara2_basic_against','t_zara2_wrap', 't_zara2_wrap2', 't_zara2_against_seq',

;     # Univ scenarios
;     't_univ1', 't_univ_obstacle', 't_univ_trapTR', 't_univ_trapTR2', 't_univ_trapTL', 't_univ_trapBL',
;     't_univ_trapBR', 't_univ_across',

;     # Hotel scenarios
;     't_hotel_against', 't_hotel_follow', 't_hotel_against_diag', 't_hotel_follow_diag', 't_hotel_cross',

;     # Dhotel scenarios
;     't_dhotel_bottopmid', 't_dhotel_bottopleft', 't_dhotel_obstaclest']


without_robot=False ; Whether or not to run a lite-version of the simulator without the robot


[t_ETH1_1]
map_name=ETH
pedestrian_datasets=["eth"] ; Starting position for the prerecorded agents
datasets_start_t = [0] ; Starting times for all the included datasets
ped_ranges=[(0, -1)] ; [start, end] range for the pedestrian datasets being use (-1 to include all agents)
## NOTE: all pos_3's are (x, y, theta)
agents_start=[] ; start pos_3's of the generated agent configs
agents_end=[] ; end pos_3's of the generated agent configs
robot_start_goal=[[8, 5, 1.5], [12, 15, 1.5]] ; start and goal pos_3's of the robot
max_time=60 ; maximum time provided for this test
write_episode_log=True ; to write the episode log at the end of the simulation

[t_ETH1_3]
map_name=ETH
pedestrian_datasets=["eth"] ; Starting position for the prerecorded agents
datasets_start_t = [0] ; Starting times for all the included datasets
ped_ranges=[(0, -1)] ; [start, end] range for the pedestrian datasets being use (-1 to include all agents)
## NOTE: all pos_3's are (x, y, theta)
agents_start=[] ; start pos_3's of the generated agent configs
agents_end=[] ; end pos_3's of the generated agent configs
robot_start_goal=[[12, 15, 1.5], [8, 5, 1.5]] ; start and goal pos_3's of the robot
max_time=60 ; maximum time provided for this test
write_episode_log=True ; to write the episode log at the end of the simulation

[t_ETH1_2]
map_name=ETH
pedestrian_datasets=["eth"] ; Starting position for the prerecorded agents
datasets_start_t = [0] ; Starting times for all the included datasets
ped_ranges=[(0, -1)] ; [start, end] range for the pedestrian datasets being use (-1 to include all agents)
## NOTE: all pos_3's are (x, y, theta)
agents_start=[] ; start pos_3's of the generated agent configs
agents_end=[] ; end pos_3's of the generated agent configs
robot_start_goal=[[6, 2.5, 1.5], [12, 15, 1.5]] ; start and goal pos_3's of the robot
max_time=60 ; maximum time provided for this test
write_episode_log=True ; to write the episode log at the end of the simulation

[t_ETH1_4]
map_name=ETH
pedestrian_datasets=["eth"] ; Starting position for the prerecorded agents
datasets_start_t = [0] ; Starting times for all the included datasets
ped_ranges=[(0, -1)] ; [start, end] range for the pedestrian datasets being use (-1 to include all agents)
## NOTE: all pos_3's are (x, y, theta)
agents_start=[] ; start pos_3's of the generated agent configs
agents_end=[] ; end pos_3's of the generated agent configs
robot_start_goal=[[12, 15, 1.5], [6, 2.5, 1.5]] ; start and goal pos_3's of the robot
max_time=60 ; maximum time provided for this test
write_episode_log=True ; to write the episode log at the end of the simulation


[t_ETH1_5]
map_name=ETH
pedestrian_datasets=["eth"] ; Starting position for the prerecorded agents
datasets_start_t = [0] ; Starting times for all the included datasets
ped_ranges=[(0, -1)] ; [start, end] range for the pedestrian datasets being use (-1 to include all agents)
## NOTE: all pos_3's are (x, y, theta)
agents_start=[] ; start pos_3's of the generated agent configs
agents_end=[] ; end pos_3's of the generated agent configs
robot_start_goal=[[12, 15, 1.5], [10, 2.5, -1.5]] ; start and goal pos_3's of the robot
max_time=60 ; maximum time provided for this test
write_episode_log=True ; to write the episode log at the end of the simulation

[t_ETH1_6]
map_name=ETH
pedestrian_datasets=["eth"] ; Starting position for the prerecorded agents
datasets_start_t = [0] ; Starting times for all the included datasets
ped_ranges=[(0, -1)] ; [start, end] range for the pedestrian datasets being use (-1 to include all agents)
## NOTE: all pos_3's are (x, y, theta)
agents_start=[] ; start pos_3's of the generated agent configs
agents_end=[] ; end pos_3's of the generated agent configs
robot_start_goal=[[10, 2.5, -1.5], [12, 15, 1.5]] ; start and goal pos_3's of the robot
max_time=60 ; maximum time provided for this test
write_episode_log=True ; to write the episode log at the end of the simulation

[t_ETH1_7]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 15.5, 0], [9.5,1,-1.5]]
max_time=60
write_episode_log=True

[t_ETH1_8]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[9.5,1,1.5], [1.5,15.5,3]]
max_time=60
write_episode_log=True

[t_ETH1_9]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[9.5,1,-1.5], [1.5, 15.5, 0]]
max_time=60
write_episode_log=True

[t_ETH1_10]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[5,1,1.5], [12.5,15.5,0]]
max_time=60
write_episode_log=True

[t_ETH1_11]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(0, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12.5,15.5,0], [5,1,1.5]]
max_time=60
write_episode_log=True

[t_ETH1_12]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[5, 1, 1.5], [12.5, 15.5, 0]]
max_time=60
write_episode_log=True

[t_ETH1_13]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12.5, 15.5, 0], [5, 1, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_14]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 15.5, 0], [9.5, 1, -1.5]]
max_time=60
write_episode_log=True

[t_ETH1_15]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[9.5, 1, 1.5], [1.5, 15.5, 3]]
max_time=60
write_episode_log=True

[t_ETH1_16]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[9.5, 1, -1.5], [1.5, 15.5, 0]]
max_time=60
write_episode_log=True

[t_ETH1_17]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[6, 2.5, 1.5], [12, 15, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_18]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12, 15, 1.5], [6, 2.5, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_19]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[8, 5, 1.5], [12, 15, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_20]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12, 15, 1.5], [8, 5, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_21]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[10, 2.5, -1.5], [12, 15, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_22]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(250, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12, 15, 1.5], [10, 2.5, -1.5]]
max_time=60
write_episode_log=True

[t_ETH1_23]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[5, 1, 1.5], [12.5, 15.5, 0]]
max_time=60
write_episode_log=True

[t_ETH1_24]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12.5, 15.5, 0], [5, 1, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_25]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 15.5, 0], [9.5, 1, -1.5]]
max_time=60
write_episode_log=True

[t_ETH1_26]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[9.5, 1, 1.5], [1.5, 15.5, 3]]
max_time=60
write_episode_log=True

[t_ETH1_27]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[9.5, 1, -1.5], [1.5, 15.5, 0]]
max_time=60
write_episode_log=True

[t_ETH1_28]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[6, 2.5, 1.5], [12, 15, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_29]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12, 15, 1.5], [6, 2.5, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_30]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[8, 5, 1.5], [12, 15, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_31]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12, 15, 1.5], [8, 5, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_32]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[10, 2.5, -1.5], [12, 15, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_33]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, -1)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12, 15, 1.5], [10, 2.5, -1.5]]
max_time=60
write_episode_log=True

[t_ETH1_34]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[5, 1, 1.5], [12.5, 15.5, 0]]
max_time=60
write_episode_log=True

[t_ETH1_35]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12.5, 15.5, 0], [5, 1, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_36]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[1.5, 15.5, 0], [9.5, 1, -1.5]]
max_time=60
write_episode_log=True

[t_ETH1_37]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[9.5, 1, 1.5], [1.5, 15.5, 3]]
max_time=60
write_episode_log=True

[t_ETH1_38]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[9.5, 1, -1.5], [1.5, 15.5, 0]]
max_time=60
write_episode_log=True

[t_ETH1_39]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[6, 2.5, 1.5], [12, 15, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_40]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12, 15, 1.5], [6, 2.5, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_41]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[8, 5, 1.5], [12, 15, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_42]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12, 15, 1.5], [8, 5, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_43]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[10, 2.5, -1.5], [12, 15, 1.5]]
max_time=60
write_episode_log=True

[t_ETH1_44]
map_name=ETH
pedestrian_datasets=["eth"]
datasets_start_t = [0]
ped_ranges=[(238, 250)]
agents_start=[]
agents_end=[]
robot_start_goal=[[12, 15, 1.5], [10, 2.5, -1.5]]
max_time=60
write_episode_log=True
